import type { Metadata } from 'next';
import { Outfit } from 'next/font/google';
import Topbar from '@/components/shared/top-bar/top-bar';
import { AppRouterCacheProvider } from '@mui/material-nextjs/v14-appRouter';
import { ThemeProvider } from '@mui/material/styles';
import theme from '../theme';

const outfit = Outfit({ subsets: ['latin'] });
import { ClerkProvider } from '@clerk/nextjs';
import './globals.css';
import Provider from '@/utils/providers';

export const metadata: Metadata = {
    title: 'Gym plans',
    description: 'Generated by create next app',
};

export default async function RootLayout({
                                             children,
                                         }: Readonly<{
    children: React.ReactNode;
}>) {

    return (
        <ClerkProvider>
            <html lang="en">
            <body className={outfit.className}>
            <Provider>
                <AppRouterCacheProvider options={{ key: 'css' }}>
                    <ThemeProvider theme={theme}>
                        <Topbar />
                        {children}
                    </ThemeProvider>
                </AppRouterCacheProvider>
            </Provider>
            </body>
            </html>
        </ClerkProvider>
    );
}
